import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f4f6f9',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  welcomeTitle: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#1a1a1a',
    textAlign: 'center',
    marginBottom: 5,
  },
  welcomeSubtitle: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 25,
  },
  cardContainer: {
    width: '100%',
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    marginBottom: 20,
  },
  cardHeader: {
    fontSize: 18,
    fontWeight: '700',
    color: '#333',
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    paddingBottom: 10,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  statusEmoji: {
    fontSize: 24,
    marginRight: 15,
    width: 30,
    textAlign: 'center',
  },
  statusDetails: {
    flex: 1,
  },
  statusLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#2b2b2b',
  },
  statusDescription: {
    fontSize: 13,
    color: '#777',
    marginTop: 2,
  },
  successContainer: {
    backgroundColor: '#d4edda',
    padding: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#c3e6cb',
    width: '100%',
    alignItems: 'center',
  },
  successText: {
    color: '#155724',
    fontWeight: '600',
    fontSize: 14,
    textAlign: 'center',
  },
  errorContainer: {
    backgroundColor: '#f8d7da',
    padding: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#f5c6cb',
    width: '100%',
    alignItems: 'center',
  },
  errorText: {
    color: '#721c24',
    fontWeight: '500',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 15,
  },
  buttonRetry: {
    backgroundColor: '#dc3545',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    elevation: 2,
  },
  buttonRetryText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
});
