import { StyleSheet, Platform } from "react-native";
import { AppColors } from "../../../theme/colors";

export const createClientesStyles = (colors: AppColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 15,
      paddingTop: Platform.OS === "ios" ? 20 : 15,
      paddingBottom: 15,
      backgroundColor: colors.surface,
      elevation: 3,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    backButton: {
      padding: 10,
      marginRight: 10,
    },
    backText: {
      fontSize: 24,
      color: colors.primary,
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: colors.text,
      flex: 1,
    },
    list: {
      padding: 15,
    },
    card: {
      backgroundColor: colors.surface,
      padding: 16,
      borderRadius: 12,
      marginBottom: 15,
      elevation: 2,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      borderLeftWidth: 5,
      borderLeftColor: colors.primary,
    },
    cardTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: colors.text,
      marginBottom: 5,
    },
    cardText: {
      fontSize: 14,
      color: colors.textSecondary,
      marginBottom: 2,
    },
    actionsRow: {
      flexDirection: "row",
      justifyContent: "flex-end",
      marginTop: 10,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      paddingTop: 10,
    },
    actionButton: {
      marginLeft: 15,
      paddingVertical: 5,
      paddingHorizontal: 10,
      borderRadius: 6,
    },
    editButton: {
      backgroundColor: colors.warning,
    },
    deleteButton: {
      backgroundColor: colors.danger,
    },
    actionText: {
      color: colors.onPrimary,
      fontWeight: "bold",
      fontSize: 12,
    },
    fab: {
      padding: 8,
      borderRadius: 20,
      backgroundColor: colors.primary,
      alignItems: "center",
      justifyContent: "center",
      minWidth: 40,
      minHeight: 40,
    },
    fabText: {
      fontSize: 20,
      color: colors.onPrimary,
      fontWeight: "bold",
    },
    searchBar: {
      backgroundColor: colors.inputBackground,
      padding: 12,
      borderRadius: 8,
      marginBottom: 10,
      marginHorizontal: 15,
      borderWidth: 1,
      borderColor: colors.border,
      color: colors.text,
    },
    filterPicker: {
      backgroundColor: colors.inputBackground,
      borderRadius: 8,
      marginBottom: 10,
      marginHorizontal: 15,
      borderWidth: 1,
      borderColor: colors.border,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: colors.overlay,
      justifyContent: "center",
      alignItems: "center",
    },
    modalContainer: {
      width: "90%",
      maxHeight: "85%",
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 20,
      elevation: 5,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: colors.text,
      marginBottom: 15,
    },
    inputLabel: {
      fontSize: 14,
      fontWeight: "600",
      color: colors.textSecondary,
      marginBottom: 5,
      marginTop: 10,
    },
    input: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 8,
      padding: 12,
      marginBottom: 15,
      fontSize: 16,
      backgroundColor: colors.inputBackground,
      color: colors.text,
    },
    modalButtons: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: 10,
    },
    modalButton: {
      flex: 1,
      padding: 15,
      borderRadius: 8,
      alignItems: "center",
    },
    cancelButton: {
      backgroundColor: colors.textMuted,
      marginRight: 10,
    },
    saveButton: {
      backgroundColor: colors.success,
      marginLeft: 10,
    },
    modalButtonText: {
      color: colors.onPrimary,
      fontWeight: "bold",
      fontSize: 16,
    },
  });
